import random

JOKES: list[tuple[str, str]] = [
    # --- Classic one-liners & wordplay ---
    ("Why don't scientists trust atoms?", "Because they make up everything! ⚛️"),
    ("I told my wife she was drawing her eyebrows too high.", "She looked surprised. 😲"),
    ("Why did the scarecrow win an award?", "Because he was outstanding in his field. 🌾"),
    ("I'm reading a book about anti-gravity.", "It's impossible to put down. 📚"),
    ("Did you hear about the mathematician who's afraid of negative numbers?", "He'll stop at nothing to avoid them. ➖"),
    ("Why do cows wear bells?", "Because their horns don't work. 🐄"),
    ("What do you call a fish without eyes?", "A fsh. 🐟"),
    ("I asked the librarian if they had books about paranoia.", "She whispered, 'They're right behind you!' 📖"),
    ("Why can't you give Elsa a balloon?", "Because she'll let it go! ❄️"),
    ("What do you call cheese that isn't yours?", "Nacho cheese! 🧀"),
    ("Why did the bicycle fall over?", "Because it was two-tired. 🚲"),
    ("I used to hate facial hair.", "But then it grew on me. 🧔"),
    ("What do you call a sleeping dinosaur?", "A dino-snore. 🦕"),
    ("Why did the golfer bring extra pants?", "In case he got a hole in one. ⛳"),
    ("What do you call a factory that makes okay products?", "A satisfactory. 🏭"),
    ("Why do seagulls fly over the sea?", "Because if they flew over the bay, they'd be bagels! 🐦"),
    ("I told my doctor I broke my arm in two places.", "He told me to stop going to those places. 🦴"),
    ("What's brown and sticky?", "A stick. 🪵"),
    ("Why don't eggs tell jokes?", "They'd crack each other up. 🥚"),
    ("I only know 25 letters of the alphabet.", "I don't know y. 🔤"),
    ("Why did the tomato turn red?", "Because it saw the salad dressing! 🍅"),
    ("What do you call a man with a rubber toe?", "Roberto. 🦶"),
    ("Why did the coach go to the bank?", "To get his quarterback. 🏈"),
    ("I'm on a seafood diet.", "I see food and I eat it. 🍽️"),
    ("What did the ocean say to the beach?", "Nothing, it just waved. 🌊"),
    ("Why did the math book look so sad?", "Because it had too many problems. 📐"),
    ("What do you call a bear with no teeth?", "A gummy bear. 🐻"),
    ("Why can't a nose be 12 inches long?", "Because then it would be a foot. 👃"),
    ("What do you call a dinosaur that crashes their car?", "Tyrannosaurus wrecks. 🦖"),
    ("Why did the invisible man turn down the job offer?", "He couldn't see himself doing it. 👻"),
    ("What do you call a pig that does karate?", "A pork chop. 🥋"),
    ("Why did the student eat his homework?", "The teacher told him it was a piece of cake. 🍰"),
    ("What do you call an alligator in a vest?", "An investigator. 🐊"),
    ("I used to be a banker.", "But I lost interest. 💸"),
    ("What do you call a fake noodle?", "An impasta. 🍝"),
    ("Why did the coffee file a police report?", "It got mugged. ☕"),
    ("What do you call a snowman with a six-pack?", "An abdominal snowman. ⛄"),
    ("Why did the picture go to jail?", "Because it was framed. 🖼️"),
    ("What do you call a boomerang that won't come back?", "A stick. 🪵"),
    ("I'm afraid of elevators.", "I'm going to start taking steps to avoid them. 🪜"),
    ("What do you call a man who can't stand?", "Neil. 🧎"),
    ("Why don't skeletons fight each other?", "They don't have the guts. 💀"),
    ("What do you call a lazy kangaroo?", "A pouch potato. 🦘"),
    ("What do you call a sad cup of coffee?", "Depresso. ☕"),
    ("What do you call a hen that counts her eggs?", "A mathema-chicken. 🐔"),
    ("What do you call a dog magician?", "A labracadabrador. 🐕"),
    ("What do you call a sleeping T-Rex?", "A stega-snore-us! 🦖"),
    ("Why can't you hear a pterodactyl go to the bathroom?", "Because the 'p' is silent. 🦕"),
    ("What do you call a funny mountain?", "Hill-arious. ⛰️"),
    ("What do you call a pony with a sore throat?", "A little hoarse. 🐴"),
    ("Why did the stadium get hot after the game?", "All the fans left. 🏟️"),
    ("What do you call two witches living together?", "Broommates. 🧹"),
    ("Why did the frog take the bus to work?", "His car got toad. 🐸"),
    ("Why don't ants get sick?", "Because they have little anty-bodies. 🐜"),
    ("What do you call a guy lying on your doorstep?", "Matt. 🚪"),
    ("Why did the clock go to the principal's office?", "For tocking too much in class. 🕐"),
    ("What do you call a bear without any ears?", "B. 🐻"),
    ("Why did the mushroom get invited to every party?", "Because he's a fungi. 🍄"),
    ("What do you call a fish wearing a crown?", "King of the sea-bass. 🐟"),
    ("Why did the astronaut break up with his girlfriend?", "He needed space. 🚀"),
    ("What do you call a row of rabbits hopping away?", "A receding hare-line. 🐰"),
    ("Why don't scientists trust stairs?", "They're always up to something. 🪜"),
    ("What do you call a duck that steals?", "A robber ducky. 🦆"),
    ("Why did the bee get married?", "Because she found her honey. 🐝"),
    ("Why did the orange stop rolling down the hill?", "It ran out of juice. 🍊"),
    ("What do you call a policeman in bed?", "An undercover cop. 👮"),
    ("What do you call a sad strawberry?", "A blueberry. 🍓"),
    ("Why did the computer go to the doctor?", "It had a virus. 💻"),
    ("What do you call a cow on a trampoline?", "A milkshake. 🥛"),
    ("Why did the banana go to the doctor?", "It wasn't peeling well. 🍌"),
    ("What do you call a group of organized crime bananas?", "A bunch of crooks. 🍌"),
    ("Why did the lettuce win the race?", "It was a-head. 🥬"),
    ("What do you call a nosy pepper?", "Jalapeño business. 🌶️"),
    ("What do you call a lazy bull?", "A bulldozer. 🐂"),
    ("What do you call a snowman tantrum?", "A meltdown. ⛄"),
    ("Why did the belt go to jail?", "It held up a pair of pants. 👖"),
    ("Why did the nurse bring a red pen to work?", "In case she needed to draw blood. 🩺"),
    ("What do you call a man lying in a pile of leaves?", "Russell. 🍂"),
    ("Why did the kid throw butter out the window?", "To see a butterfly. 🦋"),
    ("Why did the tree go to the dentist?", "To get a root canal. 🌳"),
    ("What do you call a woman who stands between two goal posts?", "Annette. ⚽"),
    ("Why is a skeleton bad at lying?", "You can see right through it. 💀"),
    ("What do you call a shoe made of a banana?", "A slipper. 🍌"),
    ("Why did the envelope go to school?", "It wanted to be a-dress-ed. ✉️"),
    ("What do you call a number that can't keep still?", "A roamin' numeral. 🔢"),
    ("What do you call a man whose car was stolen?", "Carlos. 🚗"),
    ("Why did the gym close down?", "It just didn't work out. 🏋️"),
    ("What do you call a grumpy cow?", "Moo-dy. 🐄"),
    ("Why do fish swim in salt water?", "Because pepper makes them sneeze. 🐟"),
    ("What do you call a pencil that won't write?", "Pointless. ✏️"),
    ("Why did the librarian slip on the floor?", "She was in the non-friction section. 📚"),
    ("What do you call a dog that loves cooking?", "Gordon Ramsay. 🍳"),
    ("Why did the cookie go to the doctor?", "It was feeling crummy. 🍪"),
    ("Why don't mountains get cold in winter?", "They wear snowcaps. ❄️"),
    ("What do you call a belt made of watches?", "A waist of time. ⌚"),
    ("Why did the broom get a promotion?", "It swept the competition. 🧹"),
    ("Why did the calendar go to therapy?", "It had too many dates. 📅"),
    ("What do you call a very small valentine?", "A valen-tiny. 💌"),
    ("What do you call a fish that wears a bow tie?", "So-fish-ticated. 🐠"),
    ("What do you call a broken can opener?", "A can't opener. 🥫"),
    ("Why did the man put his money in the blender?", "He wanted to make liquid assets. 💰"),
    ("What do you call a fake stone in Ireland?", "A sham-rock. 🍀"),
    ("Why did the spider go to the computer?", "To check his web site. 🕷️"),
    ("Why did the man bring a ladder to the bar?", "He heard the drinks were on the house. 🍺"),
    ("What do you call a rabbit that tells good jokes?", "A funny bunny. 🐰"),
    ("Why did the teddy bear say no to dessert?", "She was already stuffed. 🧸"),
    ("What do you call an elephant that doesn't matter?", "An irrelephant. 🐘"),
    ("What do you call a flower that runs on electricity?", "A power plant. 🌸"),
    ("Why do robots never panic?", "They have nerves of steel. 🤖"),
    ("What do you call a line of men waiting for a haircut?", "A barber queue. ✂️"),
    ("Why do birds fly south for the winter?", "It's too far to walk. 🐦"),
    ("What do you call a sad piece of toast?", "A melancholy muffin. 🍞"),
    ("Why did the burglar take a shower?", "He wanted to make a clean getaway. 🚿"),
    ("Why did the sun go to school?", "To get a little brighter. ☀️"),
    ("What do you call an overweight psychic?", "A four-chin teller. 🔮"),
    ("Why don't vampires go to barbecues?", "They don't like steak. 🧛"),
    ("What do you call a dog that loves baths?", "A shampoodle. 🐩"),
    ("Why did the pirate go on vacation?", "He needed some arr and arr. 🏴‍☠️"),
    ("What do you call a cactus that plays guitar?", "A prick-ly picker. 🌵"),
    ("Why did the chef get arrested?", "For beating an egg. 🍳"),
    ("What do you call a witch who lives at the beach?", "A sand witch. 🏖️"),
    ("Why did the blanket blush?", "It saw the pillow case. 🛏️"),
    ("What do you call a very small wind instrument?", "A harm-onica! 🎵"),
    ("Why did the sock puppet go to therapy?", "It had too many issues to handle. 🧦"),
    ("What do you call a nervous javelin thrower?", "Shakespeare. 🎭"),
    ("Why did the math teacher break up with the history teacher?", "He thought her past was too complex. 📐"),
    ("What do you call a dentist who doesn't like tea?", "Denis. 🦷"),
    ("Why did the hipster burn his tongue?", "He drank his coffee before it was cool. ☕"),
    ("What do you call a horse that can't lose?", "Sherbet. 🐴"),
    ("What do you call a vegetable that plays snooker?", "A cue-cumber. 🥒"),
    ("Why did the can crusher quit his job?", "Because it was soda pressing. 🥤"),
    ("Why do bees hum?", "Because they don't know the words. 🐝"),
    ("What do you call a cat that gets everything it wants?", "Purrr-suasive. 🐱"),
    ("Why did the drum take a nap?", "It was beat. 🥁"),
    ("What do you call a boat that never stops complaining?", "A moan-o-hull. ⛵"),
    ("Why did the computer keep freezing?", "It left too many windows open. 💻"),
    ("What do you call a dinosaur with an extensive vocabulary?", "A thesaurus. 🦕"),
    ("Why did the brick layer retire?", "He was tired of the concrete jungle. 🧱"),
    ("What do you call a man with no body and just a nose?", "Nobody nose. 👃"),
    ("Why did the two antennas get married?", "The ceremony was okay but the reception was amazing. 📡"),
    ("What do you call a cow in an earthquake?", "A milkshake. 🐄"),
    ("Why did the flashlight break up with the battery?", "She felt drained. 🔦"),
    ("What do you call a penguin in the desert?", "Lost. 🐧"),
    ("Why did the fridge hum?", "It didn't know the words. 🎵"),
    ("What do you call a grumpy pea?", "A snap pea! 🫛"),
    ("Why did the lamp fail the exam?", "It wasn't very bright. 💡"),
    ("Why did the pillow cross the road?", "It wanted to get to the other side of the bed. 🛏️"),
    ("What do you call a pile of cats?", "A meow-ntain. 🐱"),
    ("Why did the baker go to the bank?", "He needed some dough. 🍞"),
    ("What do you call a snowman that tells jokes?", "Frosty the pun-man. ⛄"),
    ("Why did the gardener win a medal?", "She really dug the competition. 🌱"),
    ("What do you call a crab that throws things?", "A lob-ster. 🦞"),
    ("Why did the skeleton go to the party alone?", "He had no body to go with. 💀"),
    ("What do you call a well-dressed lion?", "A dandy lion. 🦁"),
    ("Why did the chicken cross the playground?", "To get to the other slide. 🐔"),
    ("What do you call a dinosaur that's a lawyer?", "A sue-o-saurus. 🦖"),
    ("Why did the donut go to the dentist?", "To get a filling. 🍩"),
    ("Why did the ocean break up with the pond?", "It thought the pond was too shallow. 🌊"),
    ("What do you call a baby monkey?", "A chimp off the old block. 🐒"),
    ("Why did the music teacher get locked out?", "His keys were on the piano. 🎹"),
    ("What do you call a scared dinosaur?", "A nervous rex. 🦖"),
    ("Why did the football go to the bank?", "Someone punted it. 🏈"),
    ("What do you call a duck that works at a bakery?", "A quacker baker! 🦆🍞"),
    ("Why was the math book always complaining?", "It had too many problems. 📐"),
    ("What do you call a detective made of lettuce?", "Romaine Holmes! 🔍🥬"),
    ("Why did the elevator break up with the escalator?", "It felt taken for granted. 🛗"),
    ("Why did the cat sit on the computer?", "To keep an eye on the mouse. 🐱"),
    ("Why did the hen refuse to fight?", "She was chicken. 🐔"),
    ("What do you call a fish that tells dad jokes?", "A clown fish. 🐠"),
    ("Why did the dog sit in the shade?", "He didn't want to be a hot dog. 🐕"),
    ("Why did the egg go to school?", "To get egg-ucated. 🥚"),
    ("What do you call a lazy person who works in a bakery?", "A loafer. 🍞"),
    ("What do you call a group of unorganized cats?", "A cat-astrophe. 🐱"),
    ("Why did the book join the gym?", "It wanted to get spine-tacular. 📚"),
    ("What do you call a parade of chess pieces?", "A pawn-demonium. ♟️"),
    ("Why did the grape stop in the middle of the road?", "It ran out of juice. 🍇"),
    ("What do you call a running chicken?", "Poultry in motion. 🐔"),
    ("Why did the carpenter fall asleep on the job?", "He was board. 🪵"),
    ("What do you call a bear that's stuck in the rain?", "A drizzly bear. 🐻"),
    ("What do you call a sad trombone?", "A low note. 🎺"),
    ("Why did the astronomer break up with the moon?", "She needed more space. 🌙"),
    ("What do you call a very smart hot dog?", "A frank-stein. 🌭"),
    ("Why did the police officer go to the baseball game?", "He heard someone stole a base. ⚾"),
    ("Why did the student bring a ladder to school?", "He wanted to go to high school. 🪜"),
    ("Why did the window go to school?", "To improve its pane. 🪟"),
    ("Why do mountains make good listeners?", "They always peak at the right moment. ⛰️"),
    ("What do you call a pile of kittens?", "A kitty litter! 😺"),
    ("Why did the lemon stop rolling?", "It ran out of juice. 🍋"),
    ("What do you call a king who is 12 inches tall?", "A ruler. 👑"),
    ("Why did the tailor get in trouble?", "He was sew unprofessional. 🧵"),
    ("What do you call a horse that lives next door?", "A neigh-bor. 🐴"),
    ("Why did the grape cross the road?", "It wanted to raisin awareness. 🍇"),
    ("Why did the clock get in trouble at school?", "It kept tocking in class. 🕐"),
    ("What do you call a well-behaved snake?", "A civil serpent. 🐍"),
    ("Why did the ocean apologize?", "It was being too wavy. 🌊"),
    ("What do you call a factory that only makes mirrors?", "Something you could really see yourself working at. 🪞"),
    ("Why did the duck get kicked out of the restaurant?", "He ran up a huge bill. 🦆"),
    ("What do you call a potato that's mean to others?", "A dic-tater. 🥔"),
    ("What do you call a train loaded with toffee?", "A chew-chew train. 🚂"),
    ("Why did the envelope go to therapy?", "It couldn't let go. ✉️"),
    ("What do you call a sad lemon?", "A sour puss. 🍋"),
    ("Why did the shoe go to school?", "To get some sole education. 👟"),
    ("What do you call a bunch of dogs playing instruments?", "A pup band. 🐕"),
    ("Why did the pencil sharpener retire?", "It couldn't take the daily grind. ✏️"),
    ("What do you call a bear with no fur?", "A bare bear. 🐻"),
    ("Why did the cloud get arrested?", "For storming the castle. ⛈️"),
    ("What do you call a comedian on a plane?", "A stand-up flight. ✈️"),
    ("Why did the map get embarrassed?", "Someone was looking at its scale. 🗺️"),
    ("What do you call a fish that practices medicine?", "A sturgeon. 🐟"),
    ("What do you call a goat at sea?", "Billy Ocean. 🐐"),
    ("Why was the math teacher always calm?", "She knew how to keep things in proportion. 📐"),
    ("Why did the tomato go red at the party?", "It spotted the ketchup. 🍅"),
    ("Why did the robot go on a diet?", "It had too many bytes. 🤖"),
    ("What do you call a pirate who skips school?", "Captain Hooky. 🏴‍☠️"),
    ("Why did the tree get a haircut?", "It needed to branch out! 🌳"),
    ("Why did the broom marry the dustpan?", "They really swept each other off their feet. 🧹"),
    ("What do you call a criminal who falls asleep in court?", "A rest-arrested. 👨‍⚖️"),
    ("What do you call a lazy kangaroo?", "A pouch potato. 🦘"),
    ("Why did the bridge go to school?", "To get over things. 🌉"),
    ("What do you call a frog that parks illegally?", "Toad. 🐸"),
    ("Why did the clock eat so much?", "It was going back for seconds. ⏰"),
    ("Why did the balloon float to the ceiling?", "It was up to something. 🎈"),
    ("What do you call a caveman's fart?", "A blast from the past. 🪨"),
    ("Why did the gingerbread man take a nap?", "He was feeling crumby. 🍪"),
    ("What do you call a man with a plank on his head?", "Edward. 🪵"),
    ("What do you call a newborn kangaroo?", "A little jumper. 🦘"),
    ("Why did the ice cream truck break down?", "It had a rocky road. 🍦"),
    ("What do you call a wizard who only conjures furniture?", "A chair-mancer. 🪑"),
    ("Why did the door go to therapy?", "It couldn't stop having hang-ups. 🚪"),
    ("Why did the sailor become a poet?", "He had a way with waves. ⛵"),
    ("Why did the butter spread so far?", "It was on a roll. 🧈"),
    ("What do you call a deer with no eyes?", "No-eye-deer! 🦌"),
    ("Why did the lighthouse go to school?", "It wanted to shed some light on things. 🏮"),
    ("What do you call a very tiny cola?", "A mini-soda. 🥤"),
    ("Why did the cowboy ride his horse?", "It was too heavy to carry. 🤠"),
    ("What do you call a crocodile that wears a vest?", "An investi-gator. 🐊"),
    ("Why did the pie go to the dentist?", "Because it had a crumble. 🥧"),
    ("Why did the leaf go to the doctor?", "It was feeling a little green. 🍃"),
    ("What do you call a sleeping Roman emperor?", "Julius Snoozer. 🏛️"),
    ("Why did the stopwatch break up with the sundial?", "She wanted someone with more hands. ⏱️"),
    ("Why did the skeleton go to the library?", "To bone up on some reading. 💀"),
    ("Why did the tornado get a standing ovation?", "It really blew the crowd away. 🌪️"),
    ("What do you call a knight who is always cold?", "Sir Brr-lot. 🥶"),
    ("Why did the lettuce beat the broccoli in the race?", "It got a head start. 🥬"),
    ("What do you call a really tall fairy?", "A high-elf. 🧝"),
    ("Why did the farmer win an award?", "He was out standing in his field. 🌾"),
    ("Why did the cloud go to school?", "To get a little more precipitation. ☁️"),
    ("Why did the banana go out with the prune?", "Because it couldn't get a date. 🍌"),
    ("Why did the bowling pins get counseling?", "They kept getting knocked down. 🎳"),
    ("Why did the egg get kicked out of class?", "It kept cracking jokes. 🥚"),
    ("What do you call a ghost's favorite fruit?", "Boo-berries. 👻"),
    ("What do you call a potato that's been to finishing school?", "A chip off the old block. 🥔"),
    ("Why did the fisherman blush?", "Because the sea weed. 🎣"),
    ("What do you call a squirrel that works at a coffee shop?", "A bar-ista. 🐿️"),
    ("Why did the tire go to therapy?", "It was tired of being walked all over. 🛞"),
    ("Why did the cheese go to the gym?", "To get shredded. 🧀"),
    ("What do you call a snowman who can cook?", "An ice chef. ⛄"),
    ("Why did the moon skip dinner?", "It was full. 🌕"),
    ("What do you call a judge with no thumbs?", "Justice Fingers. ⚖️"),
    ("Why did the vegetable garden go to yoga?", "It wanted inner peas! 🧘🫛"),
    ("What do you call a sleeping pilot?", "A napilot. ✈️"),
    ("Why did the orange win the boxing match?", "It had a lot of citrus strength. 🍊"),
    ("What do you call a cow that plays guitar?", "A moo-sician. 🐄"),
    ("What do you call a nervous witch?", "A twitch. 🧙"),
    ("What do you call a man who fell through a screen door?", "A strained man. 🚪"),
    ("Why did the mop retire?", "It was wiped out. 🧹"),
    ("What do you call a baby owl that complains?", "A whoo-ner. 🦉"),
    ("What do you call a grumpy snowflake?", "An ice-olated case. ❄️"),
    ("Why did the river go to school?", "To improve its flow. 🌊"),
    ("What do you call a sleeping dragon?", "A snore-cerer. 🐉"),
    ("What do you call a sock that's lost its partner?", "Sole-itary. 🧦"),
    ("Why did the giraffe get bad grades?", "Its head was always in the clouds. 🦒"),
    ("What do you call a pig on a skateboard?", "A boar-der! 🐷🛹"),
    ("Why did the butcher become a comedian?", "He had great delivery. 🥩"),
    ("Why did the fire hydrant blush?", "It saw the dog coming. 🐕"),
    ("What do you call a man with a seagull on his head?", "Cliff. 🐦"),
    ("Why did the whale join the orchestra?", "It had great depth of sound. 🐋"),
    ("What do you call a duck that tells lies?", "A quack-er. 🦆"),
    ("Why did the envelope have a bad day?", "It was always getting licked. ✉️"),
    ("What do you call a really boring stone?", "Gravel-y dull. 🪨"),
    ("Why did the compass break up with the ruler?", "It felt like they were going in circles. 🧭"),
    ("What do you call a sneezing train?", "Achoo-choo. 🚂"),
    ("Why did the ocean go to the therapist?", "It had too many deep-seated issues. 🌊"),
    ("Why did the ghost go to the party?", "To raise the spirit. 👻"),
    ("What do you call a tooth that plays piano?", "Ivory. 🎹"),
    ("Why did the basketball court get wet?", "The players dribbled too much. 🏀"),
    ("What do you call a polite insect?", "A lady-bug. 🐞"),
    ("Why did the library card get arrested?", "It was caught checking people out. 📚"),
    ("What do you call a cat that meows backwards?", "A tac. 🐱"),
    ("Why did the bread loaf go to the doctor?", "It was feeling crumby. 🍞"),
    ("Why did the elevator get promoted?", "It rose to the occasion. 🛗"),
    ("What do you call a horse that tells jokes?", "A neigh-slapper. 🐴"),
    ("Why did the teacher wear sunglasses?", "Her students were too bright. 🕶️"),
    ("What do you call a rabbit who is always mad?", "Angry hare. 🐰"),
    ("Why did the postman get lost?", "He was going postal. 📬"),
    ("Why did the hippo wear red shoes?", "Its blue ones were in the wash. 🦛"),
    ("Why did the volcano apologize?", "It blew its top. 🌋"),
    ("What do you call a hat that flies?", "A cap-tain. 🎩"),
    ("Why did the sandwich go to the hospital?", "It had a sub-standard filling. 🥪"),
    ("What do you call a dentist who married a manicurist?", "They fought tooth and nail. 🦷"),
    ("Why did the cow go to space?", "To see the moooon. 🐄"),
    ("What do you call a ghost who works in a bakery?", "A yeast from beyond. 👻"),
    ("Why did the telephone break up with the internet?", "There was no connection. 📞"),
    ("Why did the rubber band go to school?", "It wanted to stretch its mind. 🪀"),
    ("What do you call a polite vampire?", "Count Courteous. 🧛"),
    ("What do you call a cactus on a skateboard?", "A prickle-boarder! 🌵🛹"),
    ("What do you call a steak that got knighted?", "Sir Loin! 🥩"),
    ("What do you call two monkeys sharing an account?", "Mutual funds. 🐒"),
    ("What do you call a man whose car was stolen twice?", "Carlos again. 🚗"),
    ("Why did the spoon get invited to every party?", "It was always stirring things up. 🥄"),
    ("What do you call a crowd of chess grandmasters bragging about their wins?", "Chess nuts boasting in an open foyer. ♟️"),
    ("Why did the scarecrow become a successful politician?", "He was outstanding in his field! 🌾"),
    ("What do you call a sneaky vegetable?", "A stealth-ery! 🥦"),
    ("Why did the math teacher always carry graph paper?", "He was plotting something. 📊"),
    ("What do you call a sleeping bag?", "A nap-sack. 🎒"),
    ("Why did the ocean blush?", "Because the sea-weed! 🌊"),
    ("What do you call a bear that can't make up its mind?", "A maybe-r. 🐻"),
    ("Why did the lamp post get a promotion?", "It was outstanding on the street. 💡"),
    ("What do you call a broken pencil?", "Pointless. ✏️"),
    ("Why did the tomato family stop arguing?", "They decided to ketchup later. 🍅"),
    ("What do you call a sleeping computer?", "A nap-top. 💻"),
    ("Why did the music note go to school?", "To learn its do-re-mi's. 🎵"),
    ("What do you call a fish in a fancy hat?", "So-fish-ticated! 🐟🎩"),
    ("Why did the astronaut eat lunch on the moon?", "He wanted a little space to eat. 🚀"),
    ("What do you call a running nose?", "Fast snot. 👃"),
    ("Why did the spider fail spelling?", "It kept adding too many w's. 🕷️"),
    ("What do you call a noisy ant?", "A de-ci-bell. 🐜"),
    ("Why did the scarecrow win the debate?", "His arguments had a lot of stuffing. 🌾"),
    ("What do you call a cat that works at a hospital?", "A first-aid kit-ty. 🐱"),
    ("Why did the pencil win the race?", "It drew ahead! ✏️"),
    ("What do you call a ghost that tells fibs?", "A boo-liar. 👻"),
    ("Why did the calendar blush?", "Someone kept checking out its dates. 📅"),
    ("What do you call a horse with hiccups?", "A hic-colt. 🐴"),
    ("Why did the umbrella go to school?", "It wanted to open up. ☂️"),
]


def get_random_joke() -> tuple[str, str]:
    """Return a randomly selected (setup, punchline) tuple."""
    return random.choice(JOKES)
